apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
  name: server
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: sjw980523/test-server:v12
        name: server
        env: 
        - name: MIN_NUM_CLIENTS
          value: '5'
        ports: 
        - containerPort: 8080
        volumeMounts: 
        - name: straggler-storage2
          mountPath: /server/aggregation_straggler_parameters
        - name: global-storage2
          mountPath: /server/model
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"

      volumes: 
      - name: straggler-storage2
        persistentVolumeClaim: 
          claimName: straggler-storage-claim2
      - name: global-storage2
        persistentVolumeClaim: 
          claimName: global-storage-claim2
