apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
---
apiVersion: batch/v1
kind: Job
metadata:
  name: server
  labels:
    app: server
  name: server
spec:
  template:
    metadata:
      labels:
        app: server
    spec:
      restartPolicy: Never
      containers:
      - image: sjw980523/fedavg-server:v1
        name: server
        ports: 
        - containerPort: 8080

