apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
---
apiVersion: batch/v1
kind: Job
metadata:
  name: server
  labels:
    app: server
  name: server
spec:
  template:
    metadata:
      labels:
        app: server
    spec:
      restartPolicy: Never
      containers:
      - image: sjw980523/test-server:v2.3
        name: server
        ports: 
        - containerPort: 8080
        env:
        - name: MIN_NUM_CLIENTS
          value: '5'
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: straggler-storage2
          mountPath: /server/aggregation_straggler_parameters
        - name: global-storage2
          mountPath: /server/model
      volumes:
      - name: straggler-storage2
        persistentVolumeClaim:
          claimName: straggler-storage-claim2
      - name: global-storage2
        persistentVolumeClaim:
          claimName: global-storage-claim2

